# This is a template configuration file for memy
# (https://github.com/andrewferrier/memy/) - the values below are the defaults.
#
# By default memy looks for its config file in ~/.config/memy/memy.toml.
# ****************************************************************************

# When the database is initialized for the first time, should fasd
# (https://github.com/clvv/fasd) state files or zoxide state be imported
# automatically?
import_on_first_use = true

# List of paths that won't be saved to the memy database even when noted - these
# follow the same syntax as gitignore rules: https://git-scm.com/docs/gitignore.
# Tilde (~) to represent the home directory is supported.
#
# Example: denylist = ['*.log', '*.out', '~/cachedir']
#
# There are the default patterns which are included with memy:
#
#   - *\.swp
#   - /\.git
#   - /dev
#   - /mnt
#   - /proc
#   - /run
#   - /sys
#   - COMMIT_EDITMSG
#   - MERGE_MSG
#   - \.DS_Store
#
# If you don't like any of the defaults, you can individually remove them by
# prefixing with '!':
#
# Example: denylist = ['!/dev', 'someotherpattern*.txt']
denylist = []

# When noting symlinks using memy, should the symlink be saved, or the file the
# symlink points at?
normalize_symlinks_on_note = true

# When noting files that aren't there, should a warning be emitted?
missing_files_warn_on_note = true

# When noting files that are in the denylist, should a warning be emitted?
denied_files_warn_on_note = true

# When listing files that are in the denylist (they've been added to the
# denylist after being noted), what should happen? Valid values are
# "skip-silently", "warn", "delete"
denied_files_on_list = "delete"

# When listing files, if they are inside the user's home directory,
# should they be listed as ~/directory rather than /home/user/directory?
# Only applies to the 'plain' output format (the CSV and JSON styles always use
# full paths).
use_tilde_on_list = true

# When listing, how much should *recency of file noting* dominate over
# *frequency of noting* in the sort? 0.0 means pure frequency; 1.0 means pure
# recency.
recency_bias = 0.5

# The number of days after which missing files are deleted from the database.
# If a file has been missing for longer than this duration, it will be removed.
# If this option is set to -1, missing files will never be deleted from the
# database.
missing_files_delete_from_db_after = 30

# The command used with `memy list --output-filter` to select a path or paths.
# Typically set to a file filter command like `fzf`, and will default to `fzf`,
# `fzy` or `sk` if they are installed.
memy_output_filter = ""
