# https://pip.pypa.io/en/stable/topics/configuration/#configuration-files
#
# for pip safety, read also https://www.b-list.org/weblog/2023/dec/07/pip-install-safely/
#
# sample configs:
# - https://gist.github.com/bryanveloso/328409
#
#
[install]
# per https://news.ycombinator.com/item?id=28049115, this setting should
# stop running scripts on installation, akin to [ignore-scripts] of ~/.npmrc:  (see https://pip.pypa.io/en/stable/cli/pip_download/#cmdoption-only-binary)
only-binary = :all:

# alternatively to only-binary:
#prefer-binary

# skip really fresh releases:  # note duration/delta values not (yet) supported! (see https://pip.pypa.io/en/stable/cli/pip_download/#cmdoption-uploaded-prior-to)
#uploaded-prior-to = P7D

#require-hashes
#no-deps

